//error handling
console.log('suxil');

const x = 2;
try {
    x = 2;
} catch (error) {
    console.log('found error!!');
    console.log(error.message);
}

console.log('xirish');



